/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BoothRouteImport } from './routes/booth'
import { Route as AdminRoRouteImport } from './routes/admin-ro'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminCeoRouteImport } from './routes/admin-ceo'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothRoute = BoothRouteImport.update({
  id: '/booth',
  path: '/booth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoRoute = AdminRoRouteImport.update({
  id: '/admin-ro',
  path: '/admin-ro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCeoRoute = AdminCeoRouteImport.update({
  id: '/admin-ceo',
  path: '/admin-ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-ceo': typeof AdminCeoRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-ro': typeof AdminRoRoute
  '/booth': typeof BoothRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-ceo': typeof AdminCeoRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-ro': typeof AdminRoRoute
  '/booth': typeof BoothRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-ceo': typeof AdminCeoRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-ro': typeof AdminRoRoute
  '/booth': typeof BoothRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-ceo'
    | '/admin-login'
    | '/admin-ro'
    | '/booth'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin-ceo' | '/admin-login' | '/admin-ro' | '/booth' | '/login'
  id:
    | '__root__'
    | '/'
    | '/admin-ceo'
    | '/admin-login'
    | '/admin-ro'
    | '/booth'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCeoRoute: typeof AdminCeoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRoRoute: typeof AdminRoRoute
  BoothRoute: typeof BoothRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth': {
      id: '/booth'
      path: '/booth'
      fullPath: '/booth'
      preLoaderRoute: typeof BoothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ro': {
      id: '/admin-ro'
      path: '/admin-ro'
      fullPath: '/admin-ro'
      preLoaderRoute: typeof AdminRoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ceo': {
      id: '/admin-ceo'
      path: '/admin-ceo'
      fullPath: '/admin-ceo'
      preLoaderRoute: typeof AdminCeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCeoRoute: AdminCeoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRoRoute: AdminRoRoute,
  BoothRoute: BoothRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
